[control_plane]
node-cp ansible_host=192.168.252.5

[workers]
node-w1 ansible_host=192.168.252.7
node-w2 ansible_host=192.168.252.6

[k8s:children]
control_plane
workers

[k8s:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/k8s-baremetal