---
- name: Prep all nodes for Kubernetes
  hosts: k8s
  become: true
  roles:
    - common

- name: Bootstrap the control plane
  hosts: control_plane
  become: true
  roles:
    - control_plane

- name: Join workers to the cluster
  hosts: workers
  become: true
  roles:
    - worker

- name: Install MetalLB
  hosts: control_plane
  become: true
  roles:
    - metallb

- name: Install ingress-nginx
  hosts: control_plane
  become: true
  roles:
    - ingress

- name: Install storage (local-path-provisioner)
  hosts: control_plane
  become: true
  roles:
    - storage